# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20190716_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discription',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Category'),
        ),
    ]
